### ISSUE TITLE
Android 14 Support

### ISSUE THREAD

**Issue by Justin-Jlk** [11dj/thai_idcard_reader_flutter#8]
I'm getting the following error for android 14 devices

E/EventChannel#usb_stream_channel(26127): Failed to open event stream
E/EventChannel#usb_stream_channel(26127): java.lang.SecurityException: com.example.test: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
E/EventChannel#usb_stream_channel(26127): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
E/EventChannel#usb_stream_channel(26127): 	at android.os.Parcel.createException(Parcel.java:3041)
E/EventChannel#usb_stream_channel(26127): 	at android.os.Parcel.readException(Parcel.java:3024)
E/EventChannel#usb_stream_channel(26127): 	at android.os.Parcel.readException(Parcel.java:2966)
E/EventChannel#usb_stream_channel(26127): 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6203)
E/EventChannel#usb_stream_channel(26127): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1863)
E/EventChannel#usb_stream_channel(26127): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1803)
E/EventChannel#usb_stream_channel(26127): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1791)
E/EventChannel#usb_stream_channel(26127): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:766)
E/EventChannel#usb_stream_channel(26127): 	at com.example.thai_idcard_reader_flutter.ThaiIdcardReaderFlutterPlugin.onListen(ThaiIdcardReaderFlutterPlugin.kt:157)
E/EventChannel#usb_stream_channel(26127): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:218)
E/EventChannel#usb_stream_channel(26127): 	at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(IActivityManager.java:12213)
E/EventChannel#usb_stream_channel(26127): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3188)
E/EventChannel#usb_stream_channel(26127): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2856)
E/EventChannel#usb_stream_channel(26127): 	at android.os.Binder.execTransactInternal(Binder.java:1346)
E/EventChannel#usb_stream_channel(26127): 

════════ Exception caught by services library ══════════════════════════════════
The following PlatformException was thrown while activating platform stream on channel usb_stream_channel:
PlatformException(error, com.example.test: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts, null, null)

**Comment by phirawat123** [comment]
Modified targetSdkVersion to 33 for support android 14
